name: docs_QFinance
channels:
  - conda-forge
  - defaults
dependencies:
  # Base dependencies
  - python
  - pip
  
  # Sphinx Documentation Tools
  - sphinx
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton

  # Core QFinance Dependencies (Required to import code for docs)
  - numpy
  - pandas
  - scipy
  - yfinance
  - matplotlib
  
  - pip:
    - qiskit
    - qiskit-finance
    - qiskit-aer
    - qiskit-algorithms
    - qiskit-optimization
    - qiskit-machine-learning